// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: genetic_data.proto

package health_sync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	GeneticDataService_Create_FullMethodName = "/health_sync.GeneticDataService/Create"
	GeneticDataService_Update_FullMethodName = "/health_sync.GeneticDataService/Update"
	GeneticDataService_Delete_FullMethodName = "/health_sync.GeneticDataService/Delete"
	GeneticDataService_Get_FullMethodName    = "/health_sync.GeneticDataService/Get"
	GeneticDataService_List_FullMethodName   = "/health_sync.GeneticDataService/List"
)

// GeneticDataServiceClient is the client API for GeneticDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeneticDataServiceClient interface {
	Create(ctx context.Context, in *GeneticDataCreate, opts ...grpc.CallOption) (*Void, error)
	Update(ctx context.Context, in *GeneticDataUpdate, opts ...grpc.CallOption) (*Void, error)
	Delete(ctx context.Context, in *GetById, opts ...grpc.CallOption) (*Void, error)
	Get(ctx context.Context, in *GetById, opts ...grpc.CallOption) (*GeneticDataRes, error)
	List(ctx context.Context, in *GetAllGeneticDateReq, opts ...grpc.CallOption) (*GetAllGeneticDateRes, error)
}

type geneticDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneticDataServiceClient(cc grpc.ClientConnInterface) GeneticDataServiceClient {
	return &geneticDataServiceClient{cc}
}

func (c *geneticDataServiceClient) Create(ctx context.Context, in *GeneticDataCreate, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, GeneticDataService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geneticDataServiceClient) Update(ctx context.Context, in *GeneticDataUpdate, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, GeneticDataService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geneticDataServiceClient) Delete(ctx context.Context, in *GetById, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, GeneticDataService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geneticDataServiceClient) Get(ctx context.Context, in *GetById, opts ...grpc.CallOption) (*GeneticDataRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneticDataRes)
	err := c.cc.Invoke(ctx, GeneticDataService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geneticDataServiceClient) List(ctx context.Context, in *GetAllGeneticDateReq, opts ...grpc.CallOption) (*GetAllGeneticDateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllGeneticDateRes)
	err := c.cc.Invoke(ctx, GeneticDataService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneticDataServiceServer is the server API for GeneticDataService service.
// All implementations must embed UnimplementedGeneticDataServiceServer
// for forward compatibility
type GeneticDataServiceServer interface {
	Create(context.Context, *GeneticDataCreate) (*Void, error)
	Update(context.Context, *GeneticDataUpdate) (*Void, error)
	Delete(context.Context, *GetById) (*Void, error)
	Get(context.Context, *GetById) (*GeneticDataRes, error)
	List(context.Context, *GetAllGeneticDateReq) (*GetAllGeneticDateRes, error)
	mustEmbedUnimplementedGeneticDataServiceServer()
}

// UnimplementedGeneticDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGeneticDataServiceServer struct {
}

func (UnimplementedGeneticDataServiceServer) Create(context.Context, *GeneticDataCreate) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGeneticDataServiceServer) Update(context.Context, *GeneticDataUpdate) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedGeneticDataServiceServer) Delete(context.Context, *GetById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGeneticDataServiceServer) Get(context.Context, *GetById) (*GeneticDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGeneticDataServiceServer) List(context.Context, *GetAllGeneticDateReq) (*GetAllGeneticDateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedGeneticDataServiceServer) mustEmbedUnimplementedGeneticDataServiceServer() {}

// UnsafeGeneticDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneticDataServiceServer will
// result in compilation errors.
type UnsafeGeneticDataServiceServer interface {
	mustEmbedUnimplementedGeneticDataServiceServer()
}

func RegisterGeneticDataServiceServer(s grpc.ServiceRegistrar, srv GeneticDataServiceServer) {
	s.RegisterService(&GeneticDataService_ServiceDesc, srv)
}

func _GeneticDataService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneticDataCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneticDataServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneticDataService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneticDataServiceServer).Create(ctx, req.(*GeneticDataCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneticDataService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneticDataUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneticDataServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneticDataService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneticDataServiceServer).Update(ctx, req.(*GeneticDataUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneticDataService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneticDataServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneticDataService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneticDataServiceServer).Delete(ctx, req.(*GetById))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneticDataService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneticDataServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneticDataService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneticDataServiceServer).Get(ctx, req.(*GetById))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneticDataService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllGeneticDateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneticDataServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneticDataService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneticDataServiceServer).List(ctx, req.(*GetAllGeneticDateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GeneticDataService_ServiceDesc is the grpc.ServiceDesc for GeneticDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeneticDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "health_sync.GeneticDataService",
	HandlerType: (*GeneticDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _GeneticDataService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _GeneticDataService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GeneticDataService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GeneticDataService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _GeneticDataService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "genetic_data.proto",
}
