version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: feruza1727
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - medmon
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ ping: 1 })'"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  medtrack:
    container_name: medtrack
    build: .
    depends_on:
      - mongodb
    ports:
      - "3030:3030"
    networks:
      - medmon
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=mongo
      - MONGO_PASSWORD=feruza1727
      - KAFKA_BROKER=kafka:9092

volumes:
  mongo-data:

networks:
  medmon:
    external: true
    name: medmon
    driver: bridge
